from genetic_algorithms.algorithm_wrappers.visualizations.visualization_wrapper import VisualizationSubscriber
from genetic_algorithms.algorithm_wrappers.visualizations.traveling_salesman_visualization import TravelingSalesmanVisualization
from genetic_algorithms.algorithm_wrappers.visualizations.graph_coloring_visualization import GraphColoringVisualization
from genetic_algorithms.algorithm_wrappers.visualizations.avatar_visualization import AvatarVisualization
