from genetic_algorithms.algorithm_wrappers.visualizations.visualization_wrapper import VisualizationSubscriber
from genetic_algorithms.algorithm_wrappers.visualizations.traveling_salesman_visualization import TravelingSalesmanVisualization
