from local_search.problems.base import Problem, State
from local_search.problems.traveling_salesman_problem.problem import TravelingSalesmanProblem
from local_search.problems.graph_coloring_problem.problem import GraphColoringProblem
