from genetic_algorithms.problems.base import Model, State
from genetic_algorithms.problems.traveling_salesman_problem.problem_model import TravelingSalesmanProblem
from genetic_algorithms.problems.graph_coloring_problem.problem_model import GraphColoringProblem
from genetic_algorithms.problems.magic_square.problem_model import MagicSquareProblem
