from genetic_algorithms.problems.base import Model
from genetic_algorithms.problems.traveling_salesman_problem import TravelingSalesmanModel
from genetic_algorithms.problems.graph_coloring_problem.problem_model import GraphColoringModel
