from local_search.algorithm_subscribers.visualization_subscribers.visualization_subscriber import VisualizationSubscriber
from local_search.algorithm_subscribers.visualization_subscribers.traveling_salesman_visualization import TravelingSalesmanVisualization
from local_search.algorithm_subscribers.visualization_subscribers.graph_coloring_visualization import GraphColoringVisualization
from local_search.algorithm_subscribers.visualization_subscribers.avatar_problem_visualization import AvatarProblemVisualization
from local_search.algorithm_subscribers.visualization_subscribers.limited_avatar_problem_visualization import LimitedAvatarProblemVisualization
